---
- name: update cache and install nginx
  hosts: all
  # gather_facts: false
  vars:
    package_name: nginx
    package_version: present
  tasks:
  - name: update cache
    tags: cache
    apt:
      update_cache: yes

  - name: install nginx
    tags: nginx
    package:
      name: nginx
      state: present
  
  - name: copy index.html
    copy:
      src: index.html
      dest: /var/www/html

  - name: restart nginx
    tags: never
    sysvinit:
      name: nginx
      state: restarted
      enabled: yes
    when: ansible_facts['distribution'] == "Ubuntu"
  
  - name: install vim in playbook & in inventory nano & tree in command line
    tags: vars
    package:
      name: "{{item.package_name}}"
      state: "{{item.package_state}}"
    loop:
      - { package_name: "nginx", package_state: "present"}
      - { package_name: "mariadb-server", package_state: "latest"}
      - { package_name: "curl", package_state: "absent"}
    

  - name: setup apache2
    tags: apache
    package:
      name: apache2
      state: present
    when: ansible_facts['distribution'] == "Ubuntu"
    register: my_result

  - name: restart apache2
    tags: restart_apache2
    sysvinit:
      name: apache2
      state: restarted
      enabled: yes
    when: '{{my_result.changed}}== true'

  - name: print my_result register
    tags: register
    debug:
      # msg: '{{my_result.status.restarted.changed}}'
      var: my_result

  - name: setup httpd
    tags: httpd
    package:
      name: httpd
      state: present
    when: ansible_facts['distribution'] == "Centos"