---
# handlers file for web
# - include_tasks: copy.yml
# - include_tasks: restart.yml

- name: copy_by_template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: restart_apache2
  sysvinit:
    name: '{{package_name}}'
    state: restarted
    enabled: yes